### ISSUE TITLE
For whole prices decimals are not displayed

### ISSUE THREAD

**Issue by marcoxego** [elliotnolten/lista#22]
As they says _"I'm not sure if this is a bug or a feature",_ but, when populating a price ($ 123,00)
if `decimals` are equal to **,00**
than the price will display only the `wholeNumber` **$ 123**.
The ,00 will be not displayed completely.

**Comment by elliotnolten** [comment]
thanks for reporting! can you share a screenshot of your layer names? And tell me for which search query this happens?
